/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RideStatus = IDL.Variant({
  'Ongoing' : IDL.Null,
  'Searching' : IDL.Null,
  'Accepted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const Ride = IDL.Record({
  'id' : IDL.Text,
  'status' : RideStatus,
  'driverId' : IDL.Opt(UserId),
  'destination' : Location,
  'fare' : IDL.Nat,
  'createdAt' : Timestamp,
  'pickup' : Location,
  'passengerId' : UserId,
});
export const Result_1 = IDL.Variant({ 'ok' : Ride, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Role = IDL.Variant({
  'Driver' : IDL.Null,
  'Passenger' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'phone' : IDL.Text,
});
export const DriverInfo = IDL.Record({
  'userId' : UserId,
  'lastLocation' : IDL.Opt(Location),
  'lastSeen' : Timestamp,
  'online' : IDL.Bool,
});
export const Result_2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'acceptRide' : IDL.Func([IDL.Text], [Result_1], []),
  'cancelRide' : IDL.Func([IDL.Text], [Result], []),
  'completeRide' : IDL.Func([IDL.Text], [Result_1], []),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getMyActiveRide' : IDL.Func([], [IDL.Opt(Ride)], ['query']),
  'getOnlineDrivers' : IDL.Func([], [IDL.Vec(DriverInfo)], ['query']),
  'getPendingRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getRide' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [Result_2], []),
  'rejectRide' : IDL.Func([IDL.Text], [Result], []),
  'requestRide' : IDL.Func([Location, Location], [Result_1], []),
  'setDriverOnline' : IDL.Func([IDL.Bool], [Result], []),
  'startRide' : IDL.Func([IDL.Text], [Result_1], []),
  'updateDriverLocation' : IDL.Func([IDL.Float64, IDL.Float64], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RideStatus = IDL.Variant({
    'Ongoing' : IDL.Null,
    'Searching' : IDL.Null,
    'Accepted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Location = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const Timestamp = IDL.Int;
  const Ride = IDL.Record({
    'id' : IDL.Text,
    'status' : RideStatus,
    'driverId' : IDL.Opt(UserId),
    'destination' : Location,
    'fare' : IDL.Nat,
    'createdAt' : Timestamp,
    'pickup' : Location,
    'passengerId' : UserId,
  });
  const Result_1 = IDL.Variant({ 'ok' : Ride, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Role = IDL.Variant({ 'Driver' : IDL.Null, 'Passenger' : IDL.Null });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const DriverInfo = IDL.Record({
    'userId' : UserId,
    'lastLocation' : IDL.Opt(Location),
    'lastSeen' : Timestamp,
    'online' : IDL.Bool,
  });
  const Result_2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  
  return IDL.Service({
    'acceptRide' : IDL.Func([IDL.Text], [Result_1], []),
    'cancelRide' : IDL.Func([IDL.Text], [Result], []),
    'completeRide' : IDL.Func([IDL.Text], [Result_1], []),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getMyActiveRide' : IDL.Func([], [IDL.Opt(Ride)], ['query']),
    'getOnlineDrivers' : IDL.Func([], [IDL.Vec(DriverInfo)], ['query']),
    'getPendingRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getRide' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [Result_2], []),
    'rejectRide' : IDL.Func([IDL.Text], [Result], []),
    'requestRide' : IDL.Func([Location, Location], [Result_1], []),
    'setDriverOnline' : IDL.Func([IDL.Bool], [Result], []),
    'startRide' : IDL.Func([IDL.Text], [Result_1], []),
    'updateDriverLocation' : IDL.Func([IDL.Float64, IDL.Float64], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };