/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DriverInfo {
  'userId' : UserId,
  'lastLocation' : [] | [Location],
  'lastSeen' : Timestamp,
  'online' : boolean,
}
export interface Location { 'lat' : number, 'lng' : number }
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : Ride } |
  { 'err' : string };
export type Result_2 = { 'ok' : User } |
  { 'err' : string };
export interface Ride {
  'id' : string,
  'status' : RideStatus,
  'driverId' : [] | [UserId],
  'destination' : Location,
  'fare' : bigint,
  'createdAt' : Timestamp,
  'pickup' : Location,
  'passengerId' : UserId,
}
export type RideStatus = { 'Ongoing' : null } |
  { 'Searching' : null } |
  { 'Accepted' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export type Role = { 'Driver' : null } |
  { 'Passenger' : null };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'phone' : string,
}
export type UserId = Principal;
export interface _SERVICE {
  'acceptRide' : ActorMethod<[string], Result_1>,
  'cancelRide' : ActorMethod<[string], Result>,
  'completeRide' : ActorMethod<[string], Result_1>,
  'getCurrentUser' : ActorMethod<[], [] | [User]>,
  'getMyActiveRide' : ActorMethod<[], [] | [Ride]>,
  'getOnlineDrivers' : ActorMethod<[], Array<DriverInfo>>,
  'getPendingRides' : ActorMethod<[], Array<Ride>>,
  'getRide' : ActorMethod<[string], [] | [Ride]>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'registerUser' : ActorMethod<[string, string, Role], Result_2>,
  'rejectRide' : ActorMethod<[string], Result>,
  'requestRide' : ActorMethod<[Location, Location], Result_1>,
  'setDriverOnline' : ActorMethod<[boolean], Result>,
  'startRide' : ActorMethod<[string], Result_1>,
  'updateDriverLocation' : ActorMethod<[number, number], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];