/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface Ride {
    id: string;
    status: RideStatus;
    driverId?: UserId;
    destination: Location;
    fare: bigint;
    createdAt: Timestamp;
    pickup: Location;
    passengerId: UserId;
}
export type Result_2 = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    phone: string;
}
export interface DriverInfo {
    userId: UserId;
    lastLocation?: Location;
    lastSeen: Timestamp;
    online: boolean;
}
export type Result_1 = {
    __kind__: "ok";
    ok: Ride;
} | {
    __kind__: "err";
    err: string;
};
export enum RideStatus {
    Ongoing = "Ongoing",
    Searching = "Searching",
    Accepted = "Accepted",
    Cancelled = "Cancelled",
    Completed = "Completed"
}
export enum Role {
    Driver = "Driver",
    Passenger = "Passenger"
}
export interface backendInterface {
    acceptRide(rideId: string): Promise<Result_1>;
    cancelRide(rideId: string): Promise<Result>;
    completeRide(rideId: string): Promise<Result_1>;
    getCurrentUser(): Promise<User | null>;
    getMyActiveRide(): Promise<Ride | null>;
    getOnlineDrivers(): Promise<Array<DriverInfo>>;
    getPendingRides(): Promise<Array<Ride>>;
    getRide(id: string): Promise<Ride | null>;
    getUser(id: UserId): Promise<User | null>;
    registerUser(name: string, phone: string, role: Role): Promise<Result_2>;
    rejectRide(rideId: string): Promise<Result>;
    requestRide(pickup: Location, destination: Location): Promise<Result_1>;
    setDriverOnline(online: boolean): Promise<Result>;
    startRide(rideId: string): Promise<Result_1>;
    updateDriverLocation(lat: number, lng: number): Promise<Result>;
}
import type { DriverInfo as _DriverInfo, Location as _Location, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Ride as _Ride, RideStatus as _RideStatus, Role as _Role, Timestamp as _Timestamp, User as _User, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptRide(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRide(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRide(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelRide(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRide(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRide(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeRide(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRide(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRide(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyActiveRide(): Promise<Ride | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActiveRide();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActiveRide();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnlineDrivers(): Promise<Array<DriverInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlineDrivers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlineDrivers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRides(): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRides();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRides();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRide(arg0: string): Promise<Ride | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRide(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRide(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: Role): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n21(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n21(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectRide(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRide(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRide(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestRide(arg0: Location, arg1: Location): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRide(arg0, arg1);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRide(arg0, arg1);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDriverOnline(arg0: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setDriverOnline(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDriverOnline(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async startRide(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.startRide(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRide(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDriverLocation(arg0: number, arg1: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriverLocation(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriverLocation(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DriverInfo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverInfo): DriverInfo {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RideStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Ride_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ride): Ride {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_User_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ride]): Ride | null {
    return value.length === 0 ? null : from_candid_Ride_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    phone: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n13(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    lastLocation: [] | [_Location];
    lastSeen: _Timestamp;
    online: boolean;
}): {
    userId: UserId;
    lastLocation?: Location;
    lastSeen: Timestamp;
    online: boolean;
} {
    return {
        userId: value.userId,
        lastLocation: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.lastLocation)),
        lastSeen: value.lastSeen,
        online: value.online
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RideStatus;
    driverId: [] | [_UserId];
    destination: _Location;
    fare: bigint;
    createdAt: _Timestamp;
    pickup: _Location;
    passengerId: _UserId;
}): {
    id: string;
    status: RideStatus;
    driverId?: UserId;
    destination: Location;
    fare: bigint;
    createdAt: Timestamp;
    pickup: Location;
    passengerId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_RideStatus_n5(_uploadFile, _downloadFile, value.status),
        driverId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.driverId)),
        destination: value.destination,
        fare: value.fare,
        createdAt: value.createdAt,
        pickup: value.pickup,
        passengerId: value.passengerId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Driver: null;
} | {
    Passenger: null;
}): Role {
    return "Driver" in value ? Role.Driver : "Passenger" in value ? Role.Passenger : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Ride;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Ride;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Ride_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ongoing: null;
} | {
    Searching: null;
} | {
    Accepted: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
}): RideStatus {
    return "Ongoing" in value ? RideStatus.Ongoing : "Searching" in value ? RideStatus.Searching : "Accepted" in value ? RideStatus.Accepted : "Cancelled" in value ? RideStatus.Cancelled : "Completed" in value ? RideStatus.Completed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DriverInfo>): Array<DriverInfo> {
    return value.map((x)=>from_candid_DriverInfo_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ride>): Array<Ride> {
    return value.map((x)=>from_candid_Ride_n3(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Driver: null;
} | {
    Passenger: null;
} {
    return value == Role.Driver ? {
        Driver: null
    } : value == Role.Passenger ? {
        Passenger: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
